name: Build application and create image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container: gitguardian/ggshield:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up the JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin
        cache: maven

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

    - name: Build image
      run: docker build . --tag otherdevopsgene/hello-world-server:latest

    - name: Scan image
      uses: docker://gitguardian/ggshield:latest
      run: ggshield secret scan docker otherdevopsgene/hello-world-server:latest
      env:
        GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
