name: Build application and create image

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up the JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin
        cache: maven

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package

    - name: Build image
      run: docker build . --tag otherdevopsgene/hello-world-server:latest

  sign:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: cosign-installer
      uses: sigstore/cosign-installer@v2.0.0

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::983430165732:role/github-oidc-kms-role
        aws-region: us-east-1

    - name: Sign image
      run: cosign sign --key awskms:///arn:aws:kms:us-east-1:983430165732:alias/cosign-key2 otherdevopsgene/hello-world-server:latest
